# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
minecraft_version=1.21
yarn_mappings=1.21+build.7
loader_version=0.15.11
#Fabric api
fabric_version=0.100.4+1.21

loom_version=1.7-SNAPSHOT

# Mod Properties
mod_version=1.21
maven_group=cat.szyuan.autoharvest
archives_base_name=AutoHarvest
cloth_config_version=15.0.127
#https://modrinth.com/mod/cloth-config/versions
modmenu_version=11.0.1
#https://modrinth.com/mod/modmenu/versions