org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

version=1.6.4
group=kite.autoharvest
java_version=25

minecraft_version=26.2
mod_name=AutoHarvest
mod_author=KiteJs
mod_id=autoharvest
license=MIT
credits=
description=AutoHarvest!!!
minecraft_version_range=[26.2]

neo_form_version=26.2-1

fabric_version=0.152.2+26.2
fabric_loader_version=0.19.3

neoforge_version=26.2.0.7-beta
neoforge_loader_version_range=[4,)

cloth_config_version=26.2.155
modmenu_version=20.0.0-beta.3
