license="${license}"
logoFile="assets/autoharvest/icon.png"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayTest="IGNORE_ALL_VERSION"
authors="${mod_author}"
description='''
${description}
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="cloth_config"
type="required"
versionRange="[${cloth_config_version},)"
ordering="NONE"
side="CLIENT"
