plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet project.sourceSets.main
        }
    }
}

dependencies {
    implementation "me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}"
}

